### ISSUE TITLE
Building docker image fails

### ISSUE THREAD

**Issue by Joris29** [openpbs/openpbs#1517] opened 2020-02-13 10:07 UTC
I was trying to build a docker image with a newer version of PBS but when i run a docker build,
i always get the following error:

checking for daemon coredump limit... unlimited
checking for a Python interpreter with version >= 3.5... none
configure: error: no suitable Python interpreter found
make: *** No rule to make target `dist'.  Stop.
cp: cannot stat 'pbspro-*.tar.gz': No such file or directory
sh: line 0: fg: no job control
sh: line 0: fg: no job control
error: File /root/rpmbuild/SOURCES/pbspro-19.0.0.tar.gz: No such file or directory

Steps to reproduce:
git clone https://github.com/PBSPro/pbspro.git
mv pbspro/docker/centos7/Dockerfile.build pbspro/docker/centos7/Dockerfile

edit pbspro/docker/centos7/build.sh:
#!/bin/bash
cd /src/pbspro
./autogen.sh
./configure PBS_VERSION=19.1.3 --prefix=/opt/pbs
make dist
mkdir /root/rpmbuild /root/rpmbuild/SOURCES /root/rpmbuild/SPECS
cp pbspro-*.tar.gz /root/rpmbuild/SOURCES
cp pbspro-rpmlintrc /root/rpmbuild/SOURCES
cp pbspro.spec /root/rpmbuild/SPECS
cd /root/rpmbuild/SPECS
rpmbuild -ba pbspro.spec

docker build -t test/pbspro:19.1.3 pbspro/docker/centos7/

**Comment by vstumpf** [comment] 2020-02-14 22:14
It seems like the dockerfile is pulling another image called `pbspro/pbsbase:centos7`. This should get updated, @minghui-liu can you look into this?

To get around this, you should be able to build pbsbase yourself, run this before the docker build:
`docker build -t pbspro/pbsbase:centos7 -f pbspro/docker/centos7/Dockerfile.base pbspro/docker/centos7/` You'll only have to do this once. 
Trying this out myself, I see one of the dependencies isn't installed. Add `libtool-ltdl-devel` to the list installed packages in `pbspro/docker/centos7/Dockerfile.base`

**Comment by subhasisb** [comment] 2020-02-16 11:59
We are planning to replace this functionality i the https://github.com/PBSPro/pbspro/tree/master/docker with that of https://github.com/PBSPro/pbspro/tree/master/ci, soon.

Kindly try out the functionality in the https://github.com/PBSPro/pbspro/tree/master/ci and let us know if that covers your needs

**Comment by Joris29** [comment] 2020-02-16 16:54
@subhasisb When i try this: pbspro/ci$ ./ci --start i get the following error

17:52:24 ---> No running service found
17:52:24 ---> Attempting to start container
Removing ci_pbs-build_1 ... done                                                                                                                                                                                                                     Removing network ci_ci
Creating network "ci_ci" with driver "bridge"
Creating ci_pbs-build_1 ... error                                                                                                                                                                                                                    
ERROR: for ci_pbs-build_1  Cannot start service pbs-build: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"src/docker-entrypoint\": stat src/docker-entrypoint: no such file or directory": unknown

ERROR: for pbs-build  Cannot start service pbs-build: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"src/docker-entrypoint\": stat src/docker-entrypoint: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
17:52:27 ---> Waiting for container build to complete

**Comment by subhasisb** [comment] 2020-02-16 17:24
Thanks @Joris29  we will take a look - @sandisamp can u take a look please?

**Comment by sandisamp** [comment] 2020-02-17 05:53
Hi, @Joris29 Can you specify whether you were using an alternative 'WORKDIR' for the container. Or whether you had modified the compose file for the same. Because in default settings this seems to be working.

**Comment by Joris29** [comment] 2020-02-17 08:21
Hi, @sandisamp i just do a git clone:
git clone https://github.com/PBSPro/pbspro.git
Then i cd to the ci folder:
cd pbspro/ci/
Then i run ./ci --start and i get the error

**Comment by sandisamp** [comment] 2020-02-17 09:08
Hi @Joris29 . Can you mention the docker and docker-compose versions so that I may check out if it indeed is a compatibility issue with the versions. 

Another step is to check if you have correct permissions. Running the 'ci' script with sudo might work
I found the following comment at  : https://github.com/docker/compose/issues/4039
> I've managed to fix it. I had wrong permissions and needed to run `docker-compose` as `sudo`.

If sudo does work, it implies docker-compose/docker does not have correct privileges.

**Comment by Joris29** [comment] 2020-02-17 10:45
@sandisamp 
Docker version 19.03.5, build 633a0ea838
docker-compose version 1.25.4, build unknown
Running with sudo doesn't work:
sudo ./ci --start
11:44:49 ---> failed to start ci services
11:44:49 --->  done start container

**Comment by Joris29** [comment] 2020-02-17 11:09
@sandisamp
I got a little further this time there was a problem with docker-compose not having the correct privileges.

I now get this:
12:08:14 ---> No running service found
12:08:14 ---> Attempting to start container
Removing network ci_ci
"docker images" requires at most 1 argument.
See 'docker images --help'.

Usage:  docker images [OPTIONS] [REPOSITORY[:TAG]]

List images
12:08:15 ---> command failed
12:08:15 ---> None
Creating network "ci_ci" with driver "bridge"
Pulling pbs-build (centos_7_ci_pbs:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling pbs-build (centos_7_ci_pbs:)...
ERROR: pull access denied for centos_7_ci_pbs, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
12:08:20 --->  done start container

**Comment by sandisamp** [comment] 2020-02-17 12:54
Yes this issue will  be resolved with the PR i mentioned in the discussion https://github.com/PBSPro/pbspro/pull/1521 In the meanwhile if you start afresh by cloning a new repo or deleting the hidden ".env" file in the ci folder, it should work.

The problem is even though ci wasn't successfully started, the .env file was updated in your previous attempt.

**Comment by Joris29** [comment] 2020-02-27 08:57
@sandisamp hi i saw that your PR got approved so i pulled it but i'm still having errors:

09:53:48 ---> No running service found
09:53:48 ---> Attempting to start container
Removing ci_pbs-build_1 ... done                                                                                                                                                        Removing network ci_ci
Creating network "ci_ci" with driver "bridge"
Creating ci_pbs-build_1 ... error                                                                                                                                                       
ERROR: for ci_pbs-build_1  Cannot start service pbs-build: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/src/docker-entrypoint\": stat /src/docker-entrypoint: no such file or directory": unknown

ERROR: for pbs-build  Cannot start service pbs-build: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/src/docker-entrypoint\": stat /src/docker-entrypoint: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
09:53:50 ---> Waiting for container build to complete

Steps to reproduce:
git clone https://github.com/PBSPro/pbspro.git
cd pbspro/ci/
rm .env
Then i run ./ci --start and i get the error

I also tried: 
- sudo -E ./ci --start
- sudo -E ./ci --start="ubuntu"

**Comment by sandisamp** [comment] 2020-03-22 07:31
Hi @Joris29 , sorry for the late response but i was unable to reproduce this issue. I used a seperate VM from my usual develpment VM just in case i was missing something but it does seem to work!
```
[sanidhya@centos7 git-chnf]$ git clone https://github.com/PBSPro/pbspro.git
Cloning into 'pbspro'...
remote: Enumerating objects: 21787, done.
remote: Total 21787 (delta 0), reused 0 (delta 0), pack-reused 21787
Receiving objects: 100% (21787/21787), 24.85 MiB | 3.60 MiB/s, done.
Resolving deltas: 100% (17656/17656), done.
[sanidhya@centos7 git-chnf]$ cd pbspro/ci/
[sanidhya@centos7 ci]$ ls
ci  docker-compose.yml  docker-entrypoint  do_sanitize_mode.sh  do.sh  killit.sh  Readme.md
[sanidhya@centos7 ci]$ rm .env
rm: cannot remove ‘.env’: No such file or directory
[sanidhya@centos7 ci]$ ./ci --start='ubuntu'
18:06:26 ---> No running service found
18:06:26 ---> Attempting to start container
Removing network ci_ci
WARNING: Network ci_ci not found.
Creating network "ci_ci" with driver "bridge"
Creating ci_pbs-build_1 ... done
18:06:28 ---> Waiting for container build to complete 
18:06:28 ---> Build logs can be found in /home/sanidhya/git-chnf/pbspro/ci/logs/build
18:06:58 ---> Current status ...... Get:30 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libunistring2 amd64 0.9.9-0ubuntu2 [368 kB]

18:07:28 ---> Current status ...... Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libexpat1 amd64 2.2.5-3ubuntu0.2 [80.5 kB]

18:07:58 ---> Current status ...... Get:48 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libperl5.26 amd64 5.26.1-6ubuntu0.3 [3527 kB]
.
...

18:14:28 ---> Current status ...... Get:294 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libx11-doc all 2:1.6.4-3ubuntu0.2 [2065 kB]

18:14:58 ---> Current status ...... Get:323 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-crypto amd64 2.6.1-8ubuntu2 [244 kB]

18:15:28 ---> Current status ...... Unpacking g++-7 (7.5.0-3ubuntu1~18.04) ...

18:15:58 ---> Current status ...... Setting up postgresql-10 (10.12-0ubuntu0.18.04.1) ...

18:16:28 ---> Current status ...... ### First time build is complete ###

18:16:28 ---> build is now complete
18:16:29 ---> docker commit 5f58765dbf26 ubuntu_ci_pbs:latest
18:16:39 --->  done start container 
[sanidhya@centos7 ci]$ ./ci --delete
Stopping ci_pbs-build_1 ... done
Removing ci_pbs-build_1 ... done
Removing network ci_ci
18:19:15 ---> done delete container and services
```

Please note:
* You need not remove the '.env' file, it was just a suggestion for your current scenario. This has been fixed since the PR was merged.

* Sudo should not be required to run ci if both docker and docker-compose have correct privileges set. Also check your environment for correct paths. (using 'sudo -E' was a problem for me as the path for docker-compose was not set but it resolved when i did so)

**Closed** 2022-01-17 12:20 UTC
